### PR TITLE
Data improvements

### LINKED ISSUE #23: Only remove plank recipe if the ingredients are logs
You should be able to do this by checking the `#minecraft:logs` tag.

This should fix the issue where things like Quark's and other mods' Vertical Planks, Buzzier Bees's Hive Planks, and Quark's dyed planks lose their recipes even though they're not the standard logs-to-planks recipe replaced by the mod.

### PR DESCRIPTION
**Pull request by sargunv**
* Fix some of my compat recipes which had the wrong tool assigned
* Fix disabled advancements failing to parse due to invalid parent "notfound" to clear some errors in the log. A null parent is valid afaik, and the log no longer complains.
* Override original plank recipes by placing the sawing plank recipes in the same path as the original. This fixes #23 but removes the config option that removes plank recipes, Users who want them back for some reason can use commands to swap the data pack order or just apply another data pack on top.
* Replace the preexisting generate.py with a rewritten version that I used to generate all the recipes
* Bump forge version since the previous version was broken on Linux

### CODE REVIEW

**Comment by sargunv** [comment]
The one thing here that hasn't been considered yet is load order. The the mod's data pack needs to be on top of all others for compat recipes to override correctly. Is there some way to ensure that?

**Comment by sargunv** [comment]
One solution for the above issue would be to simply distribute the compat data as a separate data pack, and only include the vanilla plank data with the mod.

**Comment by oitsjustjose** [comment]
Sorry, I've been pretty busy with work and moving to a new place but I'll be working on a proper solution for this very soon :)

**Comment by sargunv** [comment]
Looks like this won't be merged, so closing to get this out of my queue

**Pull request closed without merging**
